#!/bin/sh

rsync -rav --delete \
	--exclude '.*' \
	--exclude node_modules \
	. 'enceladus:~/eurolines-de-rest/'

ssh enceladus "\
cd ~/eurolines-de-rest
npm i
npm update
forever stop eurolines-de-rest
forever start -a --uid eurolines-de-rest index.js"
